### ISSUE TITLE
Windows 10 icons not applying in Tool-bar

### ISSUE THREAD

**Issue by juanscv** [Cirex/atom-metro-ui#5]
I a using Windows 10 but the tool-bar icons aren't themed with the Windows 10 icons even though I've selected it.

**Comment by Cirex** [comment]
I've intentionally not done tool-bar yet because the tool-bar itself seems to support a lot of various icon fonts out of the box so trying to deal with everyone's custom setup would we tedious.

Eventually there will be a configuration option to insert a Windows themed icon set into tool-bar much like tool-bar-main does. In the mean time you can use [flex-tool-bar](https://atom.io/packages/flex-tool-bar) to apply your own setup using Windows 8/10 icons.

You can find a flex-tool-bar example here:
 https://github.com/Cirex/atom-metro-ui/blob/master/resources/toolbar.json

Available icons for MDL 1.0/2.0 can be found here:
https://github.com/Cirex/atom-metro-ui/blob/master/styles/icons/utf-codes/mdl.less
https://github.com/Cirex/atom-metro-ui/blob/master/styles/icons/utf-codes/metro.less

**Comment by juanscv** [comment]
Great, I'm using flex tool-bar. It'd be good if the README should explain how to apply the icon set.
How do I get the colored hamburger menu in the README images?

**Comment by Cirex** [comment]
It will colorize the top most element automatically when you set tool-bar's icon size to 24px.

Updating the README is already on top of my todo list and I will hopefully get it done soon. I've been slacking as i'm waiting for Windows 10 to go RTM (which will hopefully be this week).
